### ISSUE TITLE
Extension inserts span tag into reddit comments

### ISSUE THREAD

**Issue by jmvalente** [guyb7/time-prices#19]
![image](https://cloud.githubusercontent.com/assets/55451/23086600/e7db61c6-f53b-11e6-8e8b-29f8f55c2b1e.png)

I don't recall if this happens when initially posting a comment on reddit or after editing an existing comment with a price listed.  I have the extension installed on my work PC, commented on reddit and went to fix a typo, when I noticed that it inserts tags into the comment. It's not easily visible (need to view the source of or edit the comment) when you've got the extension installed, but if you don't you see the raw HTML.

**Comment by guyb7** [comment]
Yep, confirmed this bug. It was there all along.
Looks like reddit just take the raw HTML of the comment and sets it as the value of the textarea.
They do reverse the formats they support (bold, tables, etc.), but they don't ignore other tags like TimePrices' span tags.

Thanks for detecting and reporting it! Need to think about they best way to solve it.

**Comment by CrustyJew** [comment]
> Looks like reddit just take the raw HTML of the comment and sets it as the value of the textarea.

No they don't. They send the textarea over in the document request just with `display:none` . Just check the element you are scanning before you insert your tag and make sure it isn't an `input[type=text]` or a `textarea` , or at least exclude those by default and add a website whitelist for it if absolutely necessary..

**Comment by guyb7** [comment]
@CrustyJew you're absolutely right, thanks for pointing that out. Will fix it soon.
